ci: add all-status-checks job

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -4,6 +4,9 @@ on:
     branches: [ main ]
   pull_request: { }
 
+permissions:
+  contents: read
+
 jobs:
   required-meta:
     permissions:
@@ -151,14 +154,24 @@ jobs:
           name: web-app
           path: frontend/build/web
 
-  build:
+  all-checks-passed:
     runs-on: ubuntu-24.04
-    name: All Build Finished
+    if: "!cancelled() && github.event_name == 'pull_request'"
     needs:
+      - test
+      - check-format
+      - lint
       - build-core
       - build-frontend
     steps:
-      - run: echo "Builds were successful"
+      - run: |
+          if [ "true" == "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') }}" ]
+          then
+            echo "A required job failed"
+            exit 1
+          else
+            echo "All required jobs passed"
+          fi
 
   deploy-frontend:
     runs-on: ubuntu-24.04
